# Generated by Django 4.1.4 on 2023-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=100)),
                ("type_1", models.TextField(max_length=20, null=True)),
                ("type_2", models.TextField(max_length=20, null=True)),
                ("total_stats", models.IntegerField()),
                ("hp", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("special_atk", models.IntegerField()),
                ("special_def", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("generation", models.IntegerField()),
                ("legendary", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="pokemon",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_name"),
        ),
    ]
