# Generated by Django 4.1.4 on 2023-02-04 20:10
import requests
from django.db import migrations

from pokemon.serializer import PokemonSerializer

SEED_URL = "https://msimon979.github.io/pokemon.json"


def seed_pokemon_data(apps, schema_editor):
    pokemon_data = requests.get(SEED_URL)

    if pokemon_data.status_code == 200:
        for k, v in pokemon_data.json().items():
            # remove id since its auto incremental
            v.pop("id")
            # change key name for the db
            v["total_stats"] = v.pop("total")
            serializer = PokemonSerializer(data=v)
            if serializer.is_valid():
                serializer.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_pokemon_data, reverse_func),
    ]
